version: "3.9"

services: 
  test-api:
    restars: always
    build: 
      context: ./server-test
      dockerfile: Dockefile 
    container_name: express_app
    volumes:
      /app/node_modules
      ./server-test:app
    ports: 
      - 5002:5002
    depends_on: 
      - mongodb
    NODE_ENV: ${NODE_ENV}
    MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb
  networks: 
    - express-api

mongodb:
  image: mongo
  restart: always
  ports:
    - 27017:27017
  environment: 
    MONGO_INITIDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
    MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  volumes:
    - mongodb-data:/data/db
  network_mode: 
    - express-api

mongo-express:
  image: mongo-express
  depends_on: 
    - mongodb
    ports:
      - 8081:8081
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_PASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123456
    volumes: 
      - mongodb-data
        network_mode
    networks: 
    - express-api
    
networks:
  express-api:
    driver: bridge

volumes: 
  mongodb-data:
    driver:
      local